dataSource:
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.jdbc.Driver
    username: root
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    password: temp1234
    logSql: true
    show_sql: true

## tO REMOVE APP NAME IN URL (Ques12) //introduction to grails
grails:
  app:
    context: /
  sitemesh:
    default:
      layout: 'main_linksharing'
  mail:
    host: "smtp.gmail.com"
    port: 465
    props:
        mail.smtp.auth: "true"
        mail.smtp.socketFactory.port: "465"
        mail.smtp.socketFactory.class: "javax.net.ssl.SSLSocketFactory"
        mail.smtp.socketFactory.fallback: "false"
    username: "csi.online2016@gmail.com"
    password: "qwerty@123456"
  controllers:
    upload:
      maxFileSize: 5242880
      maxRequestSize: 5242880

